/*
 * textTable.c
 *
 * Created on: Apr 10, 2017
 *   Author: E1218968
 * In regard to ISO 8859-1 symbols past 0xC0, refer to a GBK code table.
 * Each GBK character represents two characters in ASCII/ISO 8859-1.
 *
 * Longer lines of text that use displayTextInMultipleLines() need to have ' ' instead of spaces. The function uses ' ' to detect spacing.
 * CHANGE 11/6/18: displayTextInMultipleLines() no longer uses ' ' to detect spacing. The function will use an additional ' ' to detect the end of the string.
 * Alarms: index 0 -19
 */
#include "textTable.h"

const unsigned char *englishText[] = {
/* 0 */ "High Temp Alarm ",
/* 1 */ "Low Temp Alarm ",
/* 2 */ "Door Alarm ",
/* 3 */ "Phase Missing ",
/* 4 */ "High Temp Shutdown ",
/* 5 */ "Compressor Thermal Overload ",
/* 6 */ "Over Voltage ", //TAKEN OUT
/* 7 */ "Under Voltage ", //TAKEN OUT
/* 8 */ "Controller Board Malfunction ",
/* 9 */ "Unit Malfunction: High Pressure ",
/* 10 */ "Frost Detected: Compressor and Condenser Fan Disabled ",
/* 11 */ "Condenser Coil Temp Sensor Malfunction ",
/* 12 */ "Enclosure Inlet Air Temp Sensor Malfunction      ",
/* 13 */ "Enclosure Outlet Air Temp Sensor Malfunction ",
/* 14 */ "Compressor Overcurrent Alarm ",
/* 15 */ "Disable Switch Activated  ",
/* 16 */ "Restart Delay Active. Time Remaining: ",
/* 17 */ "Display Error ",
/* 18 */ "Operating in degraded mode using enclosure outlet air temp ",
/* 19 */ "Group Control Error ",
/* 20 */ "Enclosure Outlet Temp ",
/* 21 */ "Cond Coil Temp ",
/* 22 */ "Main Menu ",
/* 23 */ "Enter Passcode ",
/* 24 */ "User Interface ",
/* 25 */ "Cooling Set-Point ",
/* 26 */ "Cooling Differential ",
/* 27 */ "Heating Set-Point ",
/* 28 */ "Heating Differential ",
/* 29 */ "Temperature Scale ",
/* 30 */ "Differential +/- ",
/* 31 */ "Language ",
/* 32 */ "Passcode ",
/* 33 */ "Fahrenheit ",
/* 34 */ "Celsius ",
/* 35 */ "Positive ",
/* 36 */ "Negative ",
/* 37 */ "English ",
/* 38 */ "Fran鏰is ",
/* 39 */ "Deutsch ",
/* 40 */ "Italiano ",
/* 41 */ "Polski ",
/* 42 */ "Espa駉l ",
/* 43 */ "OFF ",
/* 44 */ "ON ",
/* 45 */ "System Interface ",
/* 46 */ "Door Switch ",
/* 47 */ "Disable Switch ",
/* 48 */ "Alarm Relay Output ",
/* 49 */ "Comp Restart Delay ",
/* 50 */ "Comp Current ",
/* 51 */ "System Settings ",
/* 52 */ "Current Limit Setting ",
/* 53 */ "MALF Activate ",
/* 54 */ "MALF Deactivate ",
/* 55 */ "HPC Fan On ",
/* 56 */ "HPC Fan Off ",
/* 57 */ "Normally Open ",
/* 58 */ "Normally Closed ",
/* 59 */ "Phase 1: ",
/* 60 */ "Phase 2: ",
/* 61 */ "Phase 3: ",
/* 62 */ "About ",
/* 63 */ "Control Hardware",
/* 64 */ "Control Firmware",
/* 65 */ "Display Hardware",
/* 66 */ "Display Firmware",
/* 67 */ "is set to ",
/* 68 */ "Passcode for User Interface is ON ",
/* 69 */ "Passcode for User Interface is OFF ",
/* 70 */ "Door Switch is set to Normally Open ",
/* 71 */ "Door Switch is set to Normally Close ",
/* 72 */ "Disable Switch is set to Normally Open ",
/* 73 */ "Disable Switch is set to Normally Close ",
/* 74 */ "Alarm relay output is set to Normally Open ",
/* 75 */ "Alarm relay output is set to Normally Close ",
/* 76 */ "Comp Restart Delay is set to ",
/* 77 */ "Delay ",
/* 78 */ "Cooling Set Point is set to ",
/* 79 */ "Cooling Differential is set to ",
/* 80 */ "Heating Set Point is set to ",
/* 81 */ "Heating Differential is set to ",
/* 82 */ "High Temp Alarm is set to ",
/* 83 */ "Low Temp Alarm is set to ",
/* 84 */ "Temperature Scale is set to ",
/* 85 */ "Differential +/- is set to ",
/* 86 */ "Updating Language Settings ... ",
/* 87 */ "Bootload ",
/* 88 */ "Evap Out Temp Sensor ",
/* 89 */ "Evap Out Temp Sensor is set to Present ",
/* 90 */ "Evap Out Temp Sensor is set to Absent ",
/* 91 */ "Present ",
/* 92 */ "Not Present ",
/* 93 */ "Group Control Mode ",
/* 94 */ "Mode ",
/* 95 */ "Mode Settings ",
/* 96 */ "Stand-Alone ",
/* 97 */ "Lead/Lag ",
/* 98 */ "Master/Slave ",
/* 99 */ "Stand-Alone Mode ",
/* 100 */ "No Settings ",
/* 101 */ "Lead/Lag Mode ",
/* 102 */ "Unit Identification ",
/* 103 */ "Differential Two ",
/* 104 */ "Control Strategy ",
/* 105 */ "Master/Slave Mode ",
/* 106 */ "Number of Units ",
/* 107 */ "Group Control Mode is set to Stand-Alone ",
/* 108 */ "Group Control Mode is set to Lead/Lag ",
/* 109 */ "Group Control Mode is set to Master/Slave ",
/* 110 */ "Remaining ",
};

const unsigned char *frenchText[] = {
/* 0 */ "Alarme de temp 閘ev閑 ", //
/* 1 */ "Alarme de temp basse ", //
/* 2 */ "Alarme de porte/fum閑 ", //
/* 3 */ "Phase manquante ", //
/* 4 */ "Arr阾 de temp 閘ev閑 ",
/* 5 */ "Surcharge thermique du comp ",
/* 6 */ "Surtension ",
/* 7 */ "Sous-tension ",
/* 8 */ "Dysf de la carte contr鬺eur ",
/* 9 */ "Dysf de l'unit� Pression 閘ev閑 ",
/* 10 */ "D閠ection de givre; ventilateur du compr et du condensateur d閟activ�", //
/* 11 */ "Dysf du capteur de temp du serpentin du condenseur ", //
/* 12 */ "Dysf du capteur de temp de l'entr閑 d'air du coffret ", //
/* 13 */ "Dysf du capteur de temp de la sortie d'air du coffret ", //
/* 14 */ "Alarme de surintensit�du comp ",
/* 15 */ "D閟activer activ�",
/* 16 */ "Red閙arrage D閘ai Actif. Temps Restant: ",
/* 17 */ "Erreur d'affichage ",
/* 18 */ "Operating in degraded mode using enclosure outlet air temp ",
/* 19 */ "Group Control Error ",
/* 20 */ "Temp sortie coffret ",
/* 21 */ "Temp serpentin cond ",
/* 22 */ "Menu principal ",
/* 23 */ "Entrer le mot de passe ",
/* 24 */ "Interface utilisateur ",
/* 25 */ "Valeur de refroid. ",//good
/* 26 */ "Diff de refroid. ",//good
/* 27 */ "Valeur de chauffage ", //shorten
/* 28 */ "Diff de chauffage ",
/* 29 */ "蒫helle de temp ",//good
/* 30 */ "Hyst閞閟is ",//good
/* 31 */ "Langue ",//good
/* 32 */ "Mot de passe ",//good
/* 33 */ "Fahrenheit ",
/* 34 */ "Celsius ",
/* 35 */ "positif ",
/* 36 */ "n間ativ ",
/* 37 */ "English ",
/* 38 */ "Fran鏰is ",
/* 39 */ "Deutsch ",
/* 40 */ "Italiano ",
/* 41 */ "Polski ",
/* 42 */ "Espa駉l ",
/* 43 */ "OFF ",
/* 44 */ "ON ",
/* 45 */ "Interface syst鑝e ",
/* 46 */ "Interrupteur de porte ",
/* 47 */ "Interrupteur de d閟activation ",
/* 48 */ "Sortie alarme �relais ",
/* 49 */ "D閘ai red閙arrage compresseur ",
/* 50 */ "Courant du compresseur ",
/* 51 */ "Param鑤res du syst鑝e ",
/* 52 */ "Param鑤res lim. Actuels ",
/* 53 */ "Dysf pression activ�",
/* 54 */ "Dysf pression d閟activ�",
/* 55 */ "Ventilateur de commande de pression activ�",
/* 56 */ "Ventilateur de commande de pression d閟activ�",
/* 57 */ "Normalement ouverte ",
/* 58 */ "Normalement ferm閑 ",
/* 59 */ "Phase 1: ",
/* 60 */ "Phase 2: ",
/* 61 */ "Phase 3: ",
/* 62 */ "�propos de ",
/* 63 */ "Syst de commande",
/* 64 */ "Logiciel de commande",
/* 65 */ "Syst d碼ffichage",
/* 66 */ "Logiciel affichage",
/* 67 */ "r間l��",
/* 68 */ "Le mot de passe pour l'interface utilisateur est activ ",
/* 69 */ "Le mot de passe pour l'interface utilisateur est d閟activ�",
/* 70 */ "L'alarme de porte est r間l閑 sur Normalement Ouvert ",
/* 71 */ "L'alarme de porte est r間l閑 sur Normalement Ferm�",
/* 72 */ "Le commutateur de d閟activation est Normalement Ouvert ",
/* 73 */ "Le commutateur de d閟activation est Normalement Ferm�",
/* 74 */ "La sortie du relais d'alarme est Normalement Ouverte ",
/* 75 */ "La sortie du relais d'alarme est Normalement Ferm�",
/* 76 */ "D閘ai de red閙arrage du compresseur r間l��",
/* 77 */ "Retard ",
/* 78 */ "Valeur de Refroid. R間l閑 �",//good
/* 79 */ "Diff. Refroid.               R間l��",
/* 80 */ "Valeur de Chauffage R間l閑 �",
/* 81 */ "Diff. Chauffage R間l��",
/* 82 */ "Alarme Temp Max  R間l閑 �",
/* 83 */ "Alarme Temp Min  R間l閑 �",
/* 84 */ "Echelle Temp en ",
/* 85 */ "Diff D閒ini ",
/* 86 */ "Mise �jour des param鑤res de langue ... ",
/* 87 */ "Bootload ",
/* 88 */ "Capteur temp. sortie 関aporateur ",
/* 89 */ "Le capteur temp. sortie 関aporateur est d閒ini sur Pr閟ent ",
/* 90 */ "Le capteur temp. sortie 関aporateur est d閒ini sur Absent ",
/* 91 */ "Pr閟ent ",
/* 92 */ "Pas pr閟ent ",
/* 93 */ "Mode Commande du groupe ",
/* 94 */ "Mode ",
/* 95 */ "R間lages du mode ",
/* 96 */ "Autonome ",
/* 97 */ "Avance/Retard ",
/* 98 */ "Ma顃re/Esclave ",
/* 99 */ "Mode Autonome ",
/* 100 */ "Pas de r間lage ",
/* 101 */ "Mode Avance/Retard ",
/* 102 */ "Rep閞age de l'unit�",
/* 103 */ "Diff閞entiel deux ",
/* 104 */ "Strat間ie de commande ",
/* 105 */ "Mode Ma顃re/Esclave ",
/* 106 */ "Nombre d'unit閟 ",
/* 107 */ "Mode Commande du groupe r間l��Autonome ",
/* 108 */ "Mode Commande du groupe r間l��Avance/Retard ",
/* 109 */ "Mode Commande du groupe r間l��Ma顃re/Esclave ",
};

const unsigned char *germanText[] = {
/* 0 */ "躡ertemperaturalarm ",
/* 1 */ "Untertemperaturalarm ",
/* 2 */ "T黵-/Rauchalarm ",
/* 3 */ "Fehlende Phase ",
/* 4 */ "Abschaltung bei 躡ertemperatur ",
/* 5 */ "躡erhitzung des Komp ",
/* 6 */ "躡erspannung ",
/* 7 */ "Unterspannung ",
/* 8 */ "Funktionsst鰎ung der Controllerkarte ",
/* 9 */ "Funktionsst鰎ung der Einheit : 躡erdruck ",
/* 10 */ "Frostbildung festgestellt, Komp und Verfl黶sigerl黤ter deaktiviert ", //too long so need page0
/* 11 */ "Funktionsst鰎ung des Temperatursensors am Verfl黶siger register ", //good but look better to be using page0
/* 12 */ "Funktionsst鰎ung des Temperatursensors am Lufteintritt des Geh鋟ses ",//good but look better to be using page0
/* 13 */ "Funktionsst鰎ung des Temperatursensors am Luftaustritt des Geh鋟ses ",//too long so need page0
/* 14 */ "躡erstromalarm des Komp ",
/* 15 */ "Trennschalter aktiviert ",
/* 16 */ "Verz鰃erung neu starten. Verbleibende Zeit: ",
/* 17 */ "Anzeigefehler ",
/* 18 */ "Operating in degraded mode using enclosure outlet air temp ", /*English*/
/* 19 */ "Group Control Error ",
/* 20 */ "Geh鋟seaustritt Temp ",
/* 21 */ "Verfl黶siger Temp ",
/* 22 */ "Hauptmen�",
/* 23 */ "Passwort eingeben ",
/* 24 */ "Bedienoberfl鋍he ",
/* 25 */ "Sollwert K黨len ",
/* 26 */ "Hysterese K黨len ",
/* 27 */ "Sollwert Heizen ",
/* 28 */ "Untertemperaturalarm ",
/* 29 */ "Temperaturskala ",
/* 30 */ "Hysterese ",
/* 31 */ "Sprache ",
/* 32 */ "Passwort ",
/* 33 */ "Fahrenheit ",
/* 34 */ "Celsius ",
/* 35 */ "Positiv ",
/* 36 */ "Negativ ",
/* 37 */ "English ",
/* 38 */ "Fran鏰is ",
/* 39 */ "Deutsch ",
/* 40 */ "Italiano ",
/* 41 */ "Polski ",
/* 42 */ "Espa駉l ",
/* 43 */ "AUS ",
/* 44 */ "EIN ",
/* 45 */ "Systemschnittstelle ",
/* 46 */ "T黵schalter ",
/* 47 */ "Trennschalter ",
/* 48 */ "Alarmrelaisausgang ",
/* 49 */ "Verz鰃.bei Neust Komp ",
/* 50 */ "Kompressorstrom ",
/* 51 */ "Systemeinstellungen ",
/* 52 */ "Einstell. Strombegrenz ",
/* 53 */ "Druck-St鰎g.aktivieren ",
/* 54 */ "Druck-St鰎g.deaktivier ",
/* 55 */ "Druckregler-L黤ter an ",
/* 56 */ "Druckregler-L黤ter aus ",
/* 57 */ "Schlie遝r ",
/* 58 */ "謋fner ",
/* 59 */ "Phase 1: ",
/* 60 */ "Phase 2: ",
/* 61 */ "Phase 3: ",
/* 62 */ "Info ",
/* 63 */ "Steuerungshardware",
/* 64 */ "Steuerungsfirmware",
/* 65 */ "Display-Hardware",
/* 66 */ "Display-Firmware",
/* 67 */ "ist eingestellt auf ",
/* 68 */ "Passcode f黵 Benutzeroberfl鋍he ist eingeschaltet ",
/* 69 */ "Passcode f黵 Benutzeroberfl鋍he ist ausgeschaltet ",
/* 70 */ "T黵schalter ist als Schliesser (NO) eingestellt ",
/* 71 */ "T黵schalter ist auf als 謋fner (NC) eingestellt ",
/* 72 */ "Deaktivierungsschalter ist als Schliesser (NO) eingestellt ",
/* 73 */ "Deaktivierungsschalter ist als 謋fner (NC) eingestellt ",
/* 74 */ "Alarmrelaisausgang ist als Schliesser (NO) eingestellt ",
/* 75 */ "Alarmrelaisausgang ist als 謋fner (NC) eingestellt ",
/* 76 */ "Verz鰃erung bei Neustart des Kompressors ist eingestellt auf ",
/* 77 */ "Verz鰃erung ", //use in alarmDisplayMemory()
/* 78 */ "Sollwert k黨len ist eingestellt auf ",
/* 79 */ "Hysterese k黨len ist eingestellt auf ",
/* 80 */ "Sollwert heizen ist eingestellt auf ",
/* 81 */ "Hysterese heizen ist eingestellt auf ",
/* 82 */ "躡ertemperaturalarm ist eingestellt auf ",
/* 83 */ "Untertemperaturalarm ist eingestellt auf ",
/* 84 */ "Temperaturskala ist eingestellt auf ",
/* 85 */ "Hysterese ist eingestellt auf ",
/* 86 */ "Spracheinstellungen aktualisieren ... ",
/* 87 */ "Bootload ",
/* 88 */ "Sensor Ausstr鰉temp. Verdampfer ",
/* 89 */ "Sensor Ausstr鰉temp. Verdampfer auf Vorhanden gesetzt ",
/* 90 */ "Sensor Ausstr鰉temp. Verdampfer auf Nicht vorhanden gesetzt ",
/* 91 */ "Vorhanden ",
/* 92 */ "Nicht vorhanden ",
/* 93 */ "Gruppensteuerungsmodus ",
/* 94 */ "Modus ",
/* 95 */ "Moduseinstellungen ",
/* 96 */ "Autonom ",
/* 97 */ "Vorhalt/Verz鰃erung ",
/* 98 */ "Master/Slave ",
/* 99 */ "Autonomer Modus ",
/* 100 */ "Keine Einstellungen ",
/* 101 */ "Modus Vorhalt/Verz鰃erung ",
/* 102 */ "Ger鋞ekennzeichnung ",
/* 103 */ "Differenz zwei ",
/* 104 */ "Steuerungsstrategie ",
/* 105 */ "Master/Slave-Modus ",
/* 106 */ "Anzahl der Ger鋞e ",
/* 107 */ "Gruppensteuerungsmo- -dus ist eingestellt auf Autonom ",
/* 108 */ "Gruppensteuerungsmo- -dus ist eingestellt auf Vorhalt/Verz鰃erung ",
/* 109 */ "Gruppensteuerungsmo- -dus ist eingestellt auf Master/Slave ",
};

const unsigned char *italianText[] = {
/* 0 */ "Allarme alta temp. ",
/* 1 */ "Allarme bassa temp. ",
/* 2 */ "Allarme sportello ",
/* 3 */ "Fase mancante ",
/* 4 */ "Arresto in caso di alta temp. ",
/* 5 */ "Sovraccarico termico del compressore ",
/* 6 */ "Over Voltage ", //TAKEN OUT
/* 7 */ "Under Voltage ", //TAKEN OUT
/* 8 */ "Malfunzionamento scheda di controllo ",
/* 9 */ "Malfunzionamento unit� Pressione alta ",
/* 10 */ "Rilevata formazione di ghiaccio; compressore e ventola condensatore disattivati ",
/* 11 */ "Malfunzionamento sensore temp. condensatore ",
/* 12 */ "Malfunzionamento sensore temp. ingresso aria lato armadio ",
/* 13 */ "Malfunzionamento sensore temp. uscita aria lato armadio ",
/* 14 */ "Allarme sovracorrente compressore ",
/* 15 */ "Sezionatore attivato ",
/* 16 */ "Ritardo riavvio attivato. Tempo rimanente: ",
/* 17 */ "Errore visualizzaz. ",
/* 18 */ "Operating in degraded mode using enclosure outlet air temp ",
/* 19 */ "Group Control Error ",
/* 20 */ "Temp. uscita lato armadio ",
/* 21 */ "Temp. condensatore ",
/* 22 */ "Menu principale ",
/* 23 */ "Inserire password ",
/* 24 */ "Interfaccia utente ",
/* 25 */ "Setpoint di raffredd. ",
/* 26 */ "Differ. di raffredd. ",
/* 27 */ "Setpoint di riscald. ",
/* 28 */ "Differ. di riscald. ",
/* 29 */ "Scala di temp. ",
/* 30 */ "Differenziale +/- ",
/* 31 */ "Lingua ",
/* 32 */ "Password ",
/* 33 */ "Fahrenheit ",
/* 34 */ "Celsius ",
/* 35 */ "Positivo ",
/* 36 */ "Negativo ",
/* 37 */ "English ",
/* 38 */ "Fran鏰is ",
/* 39 */ "Deutsch ",
/* 40 */ "Italiano ",
/* 41 */ "Polski ",
/* 42 */ "Espa駉l ",
/* 43 */ "OFF ",
/* 44 */ "ON ",
/* 45 */ "Interfaccia di sistema ",
/* 46 */ "Interruttore sportello ",
/* 47 */ "Sezionatore ",
/* 48 */ "Uscita rel�allarme ",
/* 49 */ "Ritardo riavvio del compressore ",
/* 50 */ "Corr. compressore ",
/* 51 */ "Impost. sistema ",
/* 52 */ "Impost. limiti corr. ",
/* 53 */ "Attivare malf. press. ",
/* 54 */ "Disattiv. malf. press. ",
/* 55 */ "Vent. contr. press. on ",
/* 56 */ "Vent. contr. press. off ",
/* 57 */ "Normalmente aperto ",
/* 58 */ "Normalmente chiuso ",
/* 59 */ "Fase 1: ",
/* 60 */ "Fase 2: ",
/* 61 */ "Fase 3: ",
/* 62 */ "Info ",
/* 63 */ "Hardware di controllo",
/* 64 */ "Firmware di controllo",
/* 65 */ "Display Hardware",
/* 66 */ "Display Firmware",
/* 67 */ "is set to ",
/* 68 */ "La password per l'interfaccia utente �ON ",
/* 69 */ "La password per l'interfaccia utente �OFF ",
/* 70 */ "L'interruttore sportello �impost. su normalmente aperto ",
/* 71 */ "L'interruttore sportello �impost. su normalmente chiuso ",
/* 72 */ "Il sezionatore �impost. su normalmente aperto ",
/* 73 */ "Il sezionatore �impost. su normalmente chiuso ",
/* 74 */ "L'uscita rel锠di allarme �impost. su normalmente aperto ",
/* 75 */ "L'uscita rel锠di allarme �impost. su normalmente chiuso ",
/* 76 */ "Il ritardo riavvio del compressore �impost. su ",
/* 77 */ "Delay ",
/* 78 */ "Il setpoint di raffreddamento �impost. a ",
/* 79 */ "Il differenziale di raffreddamento �impost. a ",
/* 80 */ "Il setpoint di riscaldamento �impost. a ",
/* 81 */ "Il differenziale di riscaldamento �impost. a ",
/* 82 */ "L'allarme di alta temp. �impost. a ",
/* 83 */ "L'allarme di bassa temp. �impost. a ",
/* 84 */ "La scala di temp. �impost. in ",
/* 85 */ "Il differenziale +/- �impost. su ",
/* 86 */ "Aggiornamento impost. lingua ... ",
/* 87 */ "Bootload ",
/* 88 */ "Sensore temp uscita evap ",
/* 89 */ "Il sensore temp uscita evap �impostato su presente ",
/* 90 */ "Il sensore temp uscita evap �impostato su assente ",
/* 91 */ "Presente ",
/* 92 */ "Non presente ",
/* 93 */ "Modalit酄controllo gruppo ",
/* 94 */ "Modalit酄",
/* 95 */ "Impostazioni modalit�",
/* 96 */ "Autonomia ",
/* 97 */ "Anticipo/ritardo ",
/* 98 */ "Master/slave ",
/* 99 */ "Modalit�autonomia ",
/* 100 */ "Nessuna impostazione ",
/* 101 */ "Modalit�anticipo/ritardo ",
/* 102 */ "Identificazione unit�",
/* 103 */ "Differenziale due ",
/* 104 */ "Strategia di controllo ",
/* 105 */ "Modalit�master/slave ",
/* 106 */ "Numero di unit�",
/* 107 */ "Modalit�controllo gruppo is set to Autonomia ",
/* 108 */ "Modalit�controllo gruppo is set to Anticipo/ritardo ",
/* 109 */ "Modalit�controllo gruppo is set to Master/slave ",
};

const unsigned char *polishText[] = {
/* 0 */ "Alarm wysokiej temperatury",
/* 1 */ "Alarm niskiej temperatury ",
/* 2 */ "Alarm drzwi ",
/* 3 */ "Brak fazy ",
/* 4 */ "Wyłączenie przy wysokiej temperaturze ",
/* 5 */ "Przeciążenie termiczne sprężarki ",
/* 6 */ "Napięcie przeciążeniowe ",
/* 7 */ "Pod napięciem ",
/* 8 */ "Usterka płyty kontrolera ",
/* 9 */ "Awaria urządzenia: wysokie ciśnienie ",
/* 10 */ "Frost Detected; Sprężarka i wentylator skraplacza wyłączone ",
/* 11 */ "Awaria czujnika temperatury cewki skraplacza ",
/* 12 */ "Usterka czujnika temperatury powietrza wlotowego obudowy ",
/* 13 */ "Usterka czujnika temperatury powietrza wylotowego obudowy ",
/* 14 */ "Alarm nadprądowy sprężarki ",
/* 15 */ "Wyłącz przełącznik aktywowany ",
/* 16 */ "Aktywne opóźnienie ponownego uruchomienia ",
/* 17 */ "Błąd wyświetlania ",
/* 18 */ "Praca w trybie awaryjnym z wykorzystaniem temperatury powietrza wylotowego z obudowy ",
/* 19 */ "Temperatura wylotowa obudowy ",
/* 20 */ "Temperatura cewki skraplacza ",
/* 21 */ "Menu główne ",
/* 22 */ "Wprowadź kod dostępu ",
/* 23 */ "Interfejs użytkownika ",
/* 24 */ "Nastawa chłodzenia ",
/* 25 */ "Dyferencjał chłodzenia ",
/* 26 */ "Nastawa ogrzewania ",
/* 27 */ "Dyferencjał ogrzewania ",
/* 28 */ "Skala temperatury ",
/* 29 */ "Mechanizm różnicowy + / - ",
/* 30 */ "Język ",
/* 31 */ "Hasło dla ",
/* 32 */ "Fahrenheit ",
/* 33 */ "Celsjusz ",
/* 34 */ "Pozytywny ",
/* 35 */ "Negatywny ",
/* 36 */ "język angielski ",
/* 37 */ "Francuski ",
/* 38 */ "Deutsch ",
/* 39 */ "Italiano ",
/* 40 */ "Polski ",
/* 41 */ "Espa駉l ",
/* 42 */ "OFF ",
/* 43 */ "ON ",
/* 44 */ "Interfejs systemu ",
/* 45 */ "Przełącznik drzwi ",
/* 46 */ "Wyłącz przełącznik ",
/* 47 */ "Wyjście przekaźnika alarmu ",
/* 48 */ "Opóźnienie ponownego uruchomienia komp",
/* 49 */ "Prąd Comp ",
/* 50 */ "Ustawienia systemowe ",
/* 51 */ "Ustawienie limitu prądu ",
/* 52 */ "MALF Aktywuj ",
/* 53 */ "MALF Dezaktywować ",
/* 54 */ "HPC Fan włączyć ",
/* 55 */ "HPC Fan wyłączyć ",
/* 56 */ "Normally otwarty ",
/* 57 */ "Normally nieczynny ",
/* 58 */ "Phase 1: ",
/* 59 */ "Phase 2: ",
/* 60 */ "Phase 3: ",
/* 61 */ "O ",
/* 62 */ "Sprzęt sterujący",
/* 63 */ "Steruj oprogramowaniem sprzętowym ",
/* 64 */ "Sprzęt wyświetlający ",
/* 65 */ "Wyświetl oprogramowanie układowe ",
/* 66 */ "jest ustawione na ",
/* 67 */ "Uaktualnij do",
/* 68 */ "Kod dostępu do interfejsu użytkownika jest włączony",
/* 69 */ "Kod dostępu do interfejsu użytkownika jest wyłączony ",
/* 70 */ "Przełącznik drzwi jest ustawiony na Normalnie otwarty ",
/* 71 */ "Przełącznik drzwi jest ustawiony na Normalnie zamknięty ",
/* 72 */ "Wyłącz przełącznik jest ustawiony na Normalnie otwarty ",
/* 73 */ "Wyłącz przełącznik jest ustawiony na Normalnie zamknięty ",
/* 74 */ "Wyjście przekaźnikowe alarmu jest ustawione na Normalnie otwarte ",
/* 75 */ "Wyjście przekaźnikowe alarmu jest ustawione na Normalnie Zamknij ",
/* 76 */ "Opóźnienie ponownego uruchomienia komp. Jest ustawione na ",
/* 77 */ "Opóźnienie ",
/* 78 */ "Nastawa chłodzenia jest ustawiona na ",
/* 79 */ "Różnica chłodzenia jest ustawiona na ",
/* 80 */ "Nastawa ogrzewania jest ustawiona na ",
/* 81 */ "Ogrzewanie różnicowe jest ustawione na ",
/* 82 */ "Alarm wysokiej temperatury jest ustawiony na ",
/* 83 */ "Alarm niskiej temperatury jest ustawiony na ",
/* 84 */ "Skala temperatury jest ustawiona na ",
/* 85 */ "Różnica +/- jest ustawiona na ",
/* 86 */ "Aktualizacja ustawień języka ",
/* 87 */ "Program rozruchowy ",
};

const unsigned char *spanishText[] = {
/* 0 */ "Alarma de alta temperatura ",
/* 1 */ "Alarma de baja temperatura ",
/* 2 */ "De puerta ",
/* 3 */ "Fase perdida ",
/* 4 */ "Apagado de alta temperatura ",
/* 5 */ "Sobrecarga en el compresor 閞mico ",
/* 6 */ "Sobrecarga de voltaje ",
/* 7 */ "Bajo voltaje ",
/* 8 */ "Falla en el tablero de control ",
/* 9 */ "Falla en la unidad: presi髇 alta ",
/* 10 */ "Compresor detector de escarcha y condensador del ventilador, deshabilitados ",
/* 11 */ "Falla en el sensor de temperatura del serpent韓 del condensador ",
/* 12 */ "Falla en el sensor de temperatura de la entrada de aire al gabinete ",
/* 13 */ "Falla en el sensor de temperatura de la salida de aire del gabinete ",
/* 14 */ "compresor Alarma de sobrecarga de corriente ",
/* 15 */ "Interruptor deshabilitado ",
/* 16 */ "Reinicio de retardo activo. Tiempo restante: ",
/* 17 */ "Error de visualizaci髇 ",
/* 18 */ "Operating in degraded mode using enclosure outlet air temp ",
/* 19 */ "Group Control Error ",
/* 20 */ "Temperatura de la salida del gabinete ",
/* 21 */ "Temperatura de condensaci髇 del serpent韓 ",
/* 22 */ "Men�principal ",
/* 23 */ "Introduce un c骴igo de acceso ",
/* 24 */ "Interfaz del usuario ",
/* 25 */ "Punto de enfriamiento ",
/* 26 */ "Diferencial de enfriamiento ",
/* 27 */ "Punto de calentamiento ",
/* 28 */ "Diferencial de calentamiento ",
/* 29 */ "Escala de temperatura ",
/* 30 */ "Diferencial +/- ",
/* 31 */ "Idioma ",
/* 32 */ "Contrase馻 ",
/* 33 */ "Fahrenheit ",
/* 34 */ "Celsius ",
/* 35 */ "Positivo ",
/* 36 */ "Negativo ",
/* 37 */ "English ",
/* 38 */ "Fran鏰is ",
/* 39 */ "Deutsch ",
/* 40 */ "Italiano ",
/* 41 */ "Polski ",
/* 42 */ "Espa駉l ",
/* 43 */ "APAGADO ",
/* 44 */ "ENCENDIDO ",
/* 45 */ "Interfaz del sistema ",
/* 46 */ "De puerta ",
/* 47 */ "Interruptor deshabilitado ",
/* 48 */ "Alarma de rel闋de salida ",
/* 49 */ "Retardo en el reincio del compresor ",
/* 50 */ "Corriente del compresor ",
/* 51 */ "Ajustes del sistema ",
/* 52 */ "Valores l韒ite actuales ",
/* 53 */ "MALF activado ",
/* 54 */ "MALF deactivado ", /*English*/
/* 55 */ "Ventilador HPC encendido ",
/* 56 */ "Ventilador HPC apagado ", /*English*/
/* 57 */ "Apertura normal ",
/* 58 */ "Cierre normal ",
/* 59 */ "Fase 1: ",
/* 60 */ "Fase 2: ",
/* 61 */ "Fase 3: ",
/* 62 */ "Acerca del sistema ",
/* 63 */ "ECU Hardware",
/* 64 */ "ECU Firmware",
/* 65 */ "DU Hardware",
/* 66 */ "DU Firmware",
/* 67 */ "est�ajustado a ",
/* 68 */ "El c骴igo de acceso para la interfaz de usuario est�activado ",
/* 69 */ "El c骴igo de acceso para la interfaz de usuario est�desactivado ",
/* 70 */ "Interruptor de la puerta est�ajustado a Normalmente Abierto ",
/* 71 */ "Interruptor de la puerta est�ajustado a Normalmente Cerrado ",
/* 72 */ "El interruptor de desactivaci髇 est�configurado como normalmente abierto ",
/* 73 */ "El interruptor de desactivaci髇 est�configurado en Normalmente cerrado ",
/* 74 */ "La salida de rel�de alarma est�configurada como Normalmente Abierta ",
/* 75 */ "La salida de rel�de alarma se establece en Normalmente cerrada ",
/* 76 */ "Comp Restart Delay est�ajustado a ",
/* 77 */ "Delay ", /*English*/
/* 78 */ "Punto de enfriamiento est�ajustado a ",
/* 79 */ "Diferencial de enfriamiento est�ajustado a ",
/* 80 */ "Punto de calentamiento est�ajustado a ",
/* 81 */ "Diferencial de calentamiento est�ajustado a ",
/* 82 */ "La alarma de alta temperatura est�ajustada a ",
/* 83 */ "Alarma de baja temperatura est�",
/* 84 */ "Escala de temperatura est�establecida en ",
/* 85 */ "Diferencial +/- se establece en ",
/* 86 */ "Actualizaci髇 de la configuraci髇 de idioma ",
/* 87 */ "Bootload ",
/* 88 */ "Evap. fuera sensor temp. ",
/* 89 */ "Evap. fuera sensor temp. fijado en presente ",
/* 90 */ "Evap. fuera sensor temp. fijado en ausente ",
/* 91 */ "Presente ",
/* 92 */ "No presente ",
/* 93 */ "Modo de control de grupos ",
/* 94 */ "Modo ",
/* 95 */ "Configuraci髇 del modo ",
/* 96 */ "Aut髇omo ",
/* 97 */ "Avance/retroceso ",
/* 98 */ "Maestro/esclavo ",
/* 99 */ "Modo aut髇omo ",
/* 100 */ "Ninguna configuraci髇 ",
/* 101 */ "Modo avance/retroceso ",
/* 102 */ "Identificaci髇 de la unidad ",
/* 103 */ "Diferencial dos ",
/* 104 */ "Estrategia de control ",
/* 105 */ "Modo maestro/esclavo ",
/* 106 */ "N鷐ero de unidades ",
/* 107 */ "Modo de control de grupos est�ajustado a Aut髇omo ",
/* 108 */ "Modo de control de grupos est�ajustado a Avance/retroceso ",
/* 109 */ "Modo de control de grupos est�ajustado a Maestro/esclavo ",
};
